const products = {
  books: [
    {
      id: 1,
      name: 'Wings of Fire',
      price: 800,
      url: '/assets/wings.jpeg',
      author: 'APJ Abdul Kalam',
      rating: 4.5,
      numOfReview: 200,
      description: 'Wings of Fire is an autography of APJ Abdul Kalam covering his early life and his work in Indian space research and missile programs. It is the story of a boy from a humble background who went on to become a key player in Indian space research/Indian missile programs and later became the president of India.',
      countAvailable: 2,
      category: 'Biography',
      originalPrice: 1000
    },
    {
      id: 2,
      name: 'The Fault in Our Stars',
      originalPrice: 390,
      url: '/assets/The_Fault_in_Our_Stars.jpg',
      author: 'John Green',
      rating: 4,
      numOfReview: 190,
      description: 'The Fault In Our Stars is a fabulous book about a young teenage girl who has been diagnosed with lung cancer and attends a cancer support group. ... Hazel and Augustus embark on a roller coaster ride of emotions, including love, sadness and romance, while searching for the author of their favourite book.',
      countAvailable: 6,
      category: 'Fiction'
    },
    {
      id: 1,
      name: 'The Pilgrimage',
      originalPrice: 900,
      url: '/assets/pilgrimage.jpg',
      author: 'Paulo Coelho',
      rating: 4.5,
      numOfReview: 220,
      description: 'The Pilgrimage (Portuguese: O Diário de Um Mago, "Diary of a Magus") is a 1987 novel by Brazilian novelist Paulo Coelho. It is a recollection of Paulo\'s experiences as he made his way across northern Spain on a pilgrimage to Santiago de Compostela. The novel serves as part adventure story, part guide to self-discovery.',
      countAvailable: 0,
      category: 'Biography',
      price: 600,
    },
    {
      id: 2,
      name: 'The Fault in Our Stars',
      originalPrice: 390,
      url: '/assets/The_Fault_in_Our_Stars.jpg',
      author: 'John Green',
      rating: 4,
      numOfReview: 190,
      description: 'The Fault In Our Stars is a fabulous book about a young teenage girl who has been diagnosed with lung cancer and attends a cancer support group. ... Hazel and Augustus embark on a roller coaster ride of emotions, including love, sadness and romance, while searching for the author of their favourite book.',
      countAvailable: 3,
      category: 'Fiction'
    },
    {
      id: 1,
      name: 'Wings of Fire',
      originalPrice: 400,
      url: '/assets/wings.jpeg',
      author: 'APJ Abdul Kalam',
      rating: 4.5,
      numOfReview: 250,
      description: 'Wings of Fire is an autography of APJ Abdul Kalam covering his early life and his work in Indian space research and missile programs. It is the story of a boy from a humble background who went on to become a key player in Indian space research/Indian missile programs and later became the president of India.',
      countAvailable: 4,
      category: 'Biography',
    },
    {
      id: 2,
      name: 'The Fault in Our Stars',
      originalPrice: 390,
      url: '/assets/The_Fault_in_Our_Stars.jpg',
      author: 'John Green',
      rating: 4,
      numOfReview: 190,
      description: 'The Fault In Our Stars is a fabulous book about a young teenage girl who has been diagnosed with lung cancer and attends a cancer support group. ... Hazel and Augustus embark on a roller coaster ride of emotions, including love, sadness and romance, while searching for the author of their favourite book.',
      countAvailable: 5,
      category: 'Fiction'
    },
    {
      id: 1,
      name: 'Wings of Fire',
      originalPrice: 400,
      url: '/assets/wings.jpeg',
      author: 'APJ Abdul Kalam',
      rating: 4.5,
      numOfReview: 200,
      description: 'Wings of Fire is an autography of APJ Abdul Kalam covering his early life and his work in Indian space research and missile programs. It is the story of a boy from a humble background who went on to become a key player in Indian space research/Indian missile programs and later became the president of India.',
      countAvailable: 2,
      category: 'Biography',
    },
    {
      id: 2,
      name: 'The Fault in Our Stars',
      originalPrice: 390,
      url: '/assets/The_Fault_in_Our_Stars.jpg',
      author: 'John Green',
      rating: 4,
      numOfReview: 190,
      description: 'The Fault In Our Stars is a fabulous book about a young teenage girl who has been diagnosed with lung cancer and attends a cancer support group. ... Hazel and Augustus embark on a roller coaster ride of emotions, including love, sadness and romance, while searching for the author of their favourite book.',
      countAvailable: 2,
      category: 'Fiction'
    },
  ]
}

export default products;